http:
  port: 8082
  host: 0.0.0.0
  base_path: "/api/i18n"
mongo:
  uri:
  database: sigma-billing
grpc:
  port: 50051
  host: 0.0.0.0
quota_path: /home/phongthien/Desktop/thudo/go-base/apps/quota/config/quota.yaml