group_quota:
  - name: free_trial
    quotas:
      adsInsert:
        resource: adsInsert
        hard: 2000
      machine:
        resource: machine
        hard: 2
  - name: pay_as_you_go
    quotas:
      adsInsert:
        resource: adsInsert
        hard: 10000
      machine:
        resource: machine
        hard: 3
